apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-k8s-deployment-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-k8s-deployment-prod
  template:
    metadata:
      labels:
        app: project-k8s-deployment-prod
    spec:
      containers:
      - name: project-k8s-deployment-prod
        image: tampoohoonm/php-project:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: project-k8s-deployment-prod
spec:
  type: LoadBalancer
  selector:
    app: project-k8s-deployment-prod
  ports:
  - protocol: TCP
    port: 81
    targetPort: 8000
    nodePort: 30081
