apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-k8s-deployment-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project-k8s-deployment-dev
  template:
    metadata:
      labels:
        app: project-k8s-deployment-dev
    spec:
      containers:
      - name: project-k8s-deployment-dev
        image: tampoohoonm/php-project:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: project-k8s-deployment-dev
spec:
  type: LoadBalancer
  selector:
    app: project-k8s-deployment-dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30080
